spring:
  application:
    name: "varta-ingestion-svc"


  datasource:
    pgsql:
      url: "jdbc:postgresql://localhost:5432/ingestion-service-db"
      username: "postgres"
      password: "zxca"
      driver-class-name: "org.postgresql.Driver"

      hikari:
        pool-name: "pgsql-hikari-pool"
        maximum-pool-size: 20

      jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

    # Mysql datasource
    mysql:
      url: "jdbc:mysql://localhost:3307/sf_web_001"
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    # Redis
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: never
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
      platform: pgsql

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    show-sql: true